"""init_tables

Revision ID: 1c22f7296d05
Revises:
Create Date: 2026-01-27 15:54:00.519764

"""

from typing import Sequence, Union

import database.types.ulid
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c22f7296d05"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_buckets",
        sa.Column("updated_datetime", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_datetime", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("h3_index", sa.BigInteger(), nullable=False),
        sa.Column("h3_resolution", sa.Integer(), nullable=False),
        sa.Column("parent_h3", sa.BigInteger(), nullable=True),
        sa.Column("canonical_name", sa.TEXT(), nullable=True),
        sa.Column("canonical_name_normalized", sa.TEXT(), nullable=True),
        sa.Column(
            "center_point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", srid=4326, dimension=2, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column(
            "hexagon_boundary",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON", srid=4326, dimension=2, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("property_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_geo_buckets_center_point",
        "geo_buckets",
        ["center_point"],
        unique=False,
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.create_index("idx_geo_buckets_h3", "geo_buckets", ["h3_index"], unique=False, if_not_exists=True)
    op.create_index(
        "idx_geo_buckets_hexagon_boundary",
        "geo_buckets",
        ["hexagon_boundary"],
        unique=False,
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.create_index(
        "idx_geo_buckets_name_trgm",
        "geo_buckets",
        ["canonical_name_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"canonical_name_normalized": "gin_trgm_ops"},
        if_not_exists=True,
    )
    op.create_index("idx_geo_buckets_parent", "geo_buckets", ["parent_h3"], unique=False)
    op.create_index("idx_geo_buckets_resolution", "geo_buckets", ["h3_resolution"], unique=False)
    op.create_index(op.f("ix_geo_buckets_h3_index"), "geo_buckets", ["h3_index"], unique=True)
    op.create_index(op.f("ix_geo_buckets_id"), "geo_buckets", ["id"], unique=False)
    op.create_index(op.f("ix_geo_buckets_parent_h3"), "geo_buckets", ["parent_h3"], unique=False)
    op.create_table(
        "properties",
        sa.Column("updated_datetime", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_datetime", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", database.types.ulid.ULIDType(length=26), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("location_name", sa.TEXT(), nullable=False),
        sa.Column("location_name_normalized", sa.TEXT(), nullable=False),
        sa.Column(
            "coordinates",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("h3_index_r8", sa.BigInteger(), nullable=False),
        sa.Column("h3_index_r9", sa.BigInteger(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("geo_bucket_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["geo_bucket_id"], ["geo_buckets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_properties_bucket", "properties", ["geo_bucket_id"], unique=False)
    op.create_index(
        "idx_properties_coordinates",
        "properties",
        ["coordinates"],
        unique=False,
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.create_index("idx_properties_h3_r8", "properties", ["h3_index_r8"], unique=False)
    op.create_index("idx_properties_h3_r9", "properties", ["h3_index_r9"], unique=False)
    op.create_index(
        "idx_properties_name_trgm",
        "properties",
        ["location_name_normalized"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"location_name_normalized": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_properties_h3_index_r8"), "properties", ["h3_index_r8"], unique=False)
    op.create_index(op.f("ix_properties_h3_index_r9"), "properties", ["h3_index_r9"], unique=False)
    op.create_index(op.f("ix_properties_id"), "properties", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_id"), table_name="properties")
    op.drop_index(op.f("ix_properties_h3_index_r9"), table_name="properties")
    op.drop_index(op.f("ix_properties_h3_index_r8"), table_name="properties")
    op.drop_index(
        "idx_properties_name_trgm",
        table_name="properties",
        postgresql_using="gin",
        postgresql_ops={"location_name_normalized": "gin_trgm_ops"},
    )
    op.drop_index("idx_properties_h3_r9", table_name="properties")
    op.drop_index("idx_properties_h3_r8", table_name="properties")
    op.drop_index("idx_properties_coordinates", table_name="properties", postgresql_using="gist")
    op.drop_index("idx_properties_bucket", table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_geo_buckets_parent_h3"), table_name="geo_buckets")
    op.drop_index(op.f("ix_geo_buckets_id"), table_name="geo_buckets")
    op.drop_index(op.f("ix_geo_buckets_h3_index"), table_name="geo_buckets")
    op.drop_index("idx_geo_buckets_resolution", table_name="geo_buckets")
    op.drop_index("idx_geo_buckets_parent", table_name="geo_buckets")
    op.drop_index(
        "idx_geo_buckets_name_trgm",
        table_name="geo_buckets",
        postgresql_using="gin",
        postgresql_ops={"canonical_name_normalized": "gin_trgm_ops"},
    )
    op.drop_index("idx_geo_buckets_hexagon_boundary", table_name="geo_buckets", postgresql_using="gist")
    op.drop_index("idx_geo_buckets_h3", table_name="geo_buckets")
    op.drop_index("idx_geo_buckets_center_point", table_name="geo_buckets", postgresql_using="gist")
    op.drop_table("geo_buckets")
    # ### end Alembic commands ###
